{% set version = "3.4.0.2" %}

package:
  name: glances
  version: {{ version }}

source:
  fn: Glances-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/G/Glances/Glances-{{ version }}.tar.gz
  sha256: 859f863bd9a961c5022c29f24898c02ec15a043034e664a9f8bc7dc1ca794e71

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - glances = glances:main

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - psutil >=5.6.7
    - defusedxml
    - packaging
    - ujson >=5.4.0
    {% if noarch_platform == "win" %}
    - __win
    - bottle
    - requests
    {% else %}
    - __unix
    {% endif %}

test:
  requires:
    - pip

  imports:
    - glances

  commands:
    - pip check
    - glances --help

about:
  home: https://github.com/nicolargo/glances
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: A cross-platform curses-based monitoring tool

extra:
  recipe-maintainers:
    - jakirkham
