{% set version = "3.0.2" %}

package:
  name: glances
  version: {{ version }}

source:
  fn: Glances-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/G/Glances/Glances-{{ version }}.tar.gz
  sha256: 5eca4da689e4e2f98a637b38c9b72549998ac9f15cedbfb16626d8709df6dd25

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - glances = glances:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - psutil >=2.0.0

test:
  imports:
    - glances

  commands:
    - glances --help

about:
  home: https://github.com/nicolargo/glances
  license: LGPL 3
  license_family: LGPL
  license_file: COPYING
  summary: 'A cross-platform curses-based monitoring tool'

extra:
  recipe-maintainers:
    - jakirkham
