{% set version = "3.1.3" %}

package:
  name: glances
  version: {{ version }}

source:
  fn: Glances-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/G/Glances/Glances-{{ version }}.tar.gz
  sha256: dc426f90e52a15004b8205ab4775a8002051ba36166097585caf62aa627e7f91

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - glances = glances:main

requirements:
  build:
    - python
    - pip

  run:
    - python
    - psutil >=5.3.0
    - future

test:
  imports:
    - glances

  commands:
    - glances --help

about:
  home: https://github.com/nicolargo/glances
  license: LGPL 3
  license_family: LGPL
  license_file: COPYING
  summary: 'A cross-platform curses-based monitoring tool'

extra:
  recipe-maintainers:
    - jakirkham
