{% set version = "3.3.0.2" %}

package:
  name: glances
  version: {{ version }}

source:
  fn: Glances-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/G/Glances/Glances-{{ version }}.tar.gz
  sha256: d830e1b71dbf098cc345d1a932d3104a472118ab46312b679612f5e81cbcb564

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - glances = glances:main

requirements:
  host:
    - python >=2.7,<3|>=3.4
    - pip

  run:
    - python >=2.7,<3|>=3.4
    - psutil >=5.3.0
    - defusedxml
    - future
    - packaging
    {% if noarch_platform == "win" %}
    - __win
    - bottle
    - requests
    {% else %}
    - __unix
    {% endif %}

test:
  requires:
    - pip

  imports:
    - glances

  commands:
    - pip check
    - glances --help

about:
  home: https://github.com/nicolargo/glances
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: A cross-platform curses-based monitoring tool

extra:
  recipe-maintainers:
    - jakirkham
