{% set version = "4.5.2" %}
{% set python_min = "3.10" %}

package:
  name: glances
  version: {{ version }}

source:
  fn: glances-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/g/glances/glances-{{ version }}.tar.gz
  sha256: e150e100b328a419d5003a4d54c02a4d78b0a1f5782f0aa0816877ddbe5881e9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - glances = glances:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - psutil >=5.6.7
    - defusedxml
    - packaging
    - jinja2
    - pyinstrument >=5.1.2
    - shtab

test:
  requires:
    - pip
    - python {{ python_min }}

  imports:
    - glances

  commands:
    - pip check
    - glances --help

about:
  home: https://github.com/nicolargo/glances
  license: LGPL-3.0-or-later
  license_file: COPYING
  summary: A cross-platform curses-based monitoring tool

extra:
  recipe-maintainers:
    - jakirkham
    - ConorForgie
    - gabrielcnr
